version: 2
models:
  - name: dim_channels
    description: "A dimension table containing channel metadata."
    columns:
      - name: channel_id
        description: "The unique identifier for each Telegram channel."
        tests:
          - unique
          - not_null
  
  - name: dim_dates
    description: "A dimension table for time-based analysis."
    columns:
      - name: date_day
        description: "The unique identifier for each date."
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "A fact table with one row per message and key metrics."
    columns:
      - name: message_id
        description: "The unique identifier for each message."
        tests:
          - unique
          - not_null
      - name: channel_id
        description: "Foreign key to the dim_channels table."
        tests:
          - not_null